# Starter pipeline
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(fdb0d1e7-7db9-4801-b846-25dc3f93f1ad)'
    appType: 'webApp'
    appName: 'AzureDevW'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '*.tests/*.tests.csproj'
    arguments: '--no-restore --no-build --configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'config'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
